# Generated by Django 5.2.5 on 2025-08-22 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_rename_name_testimonial_customer_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonial',
            name='customer_name',
            field=models.CharField(max_length=255),
        ),
    ]
