# Generated by Django 5.2.5 on 2025-08-22 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_testimonial_customer_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slider',
            name='image',
            field=models.ImageField(upload_to='slider_images/'),
        ),
    ]
