# Generated by Django 5.2.5 on 2025-08-23 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_remove_companyinfo_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testimonial',
            name='customer_name',
        ),
        migrations.RemoveField(
            model_name='testimonial',
            name='message',
        ),
        migrations.AddField(
            model_name='testimonial',
            name='designation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='feedback',
            field=models.TextField(default='No feedback provided.'),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='name',
            field=models.CharField(default='Anonymous', max_length=100),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='rating',
            field=models.PositiveSmallIntegerField(default=5),
        ),
    ]
